### ISSUE TITLE
getting the equation of the plan cutting the ellipsoid in two

### ISSUE THREAD

**Issue by pdeman** [minillinim/ellipsoid#1]
Hi,

The code worked very well on my data, now I am trying to get the equation of the plan which cut the ellipsoid in two. It must be possible using center and rotation but I don't find how to do that.
I have to take out of the rotation matrix a vector giving me the orientation of the longest axis.

Do you know how I can get this vector ?

Regards,

**Comment by minillinim** [comment]
This?

https://math.stackexchange.com/questions/82151/find-the-equation-of-the-plane-passing-through-a-point-and-a-vector-orthogonal
