### ISSUE TITLE
Ellipsoid that best fits a percentage of the points

### ISSUE THREAD

**Issue by marnunez** [minillinim/ellipsoid#2]
Hi! This method works really nice with my data. However, I was recently asked to get the best ellipsoid that fits 95% of the points. How could this be achieved with the current setup? Can the tolerance be tweaked to fit certain amount of points? Or should I be looking for another method?

**Comment by minillinim** [comment]
You'll have to forgive me, it's been a long time since I had to solve this problem so I've forgotten most of the maths.
